### ISSUE TITLE
Images for the Wiki

### ISSUE THREAD

**Issue by RotaruDan** [RotaruDan/rage-analytics#1]
![image](https://cloud.githubusercontent.com/assets/5658058/10453220/cf1e8db8-71aa-11e5-9907-4e9d1440c3d8.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10453565/7c62f818-71ad-11e5-9b2c-bdd6fddf7aae.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10462261/01ec6052-71de-11e5-866c-04e25a96ffcb.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10462334/76d8a092-71de-11e5-8b57-5f011d0d578e.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10462405/d14eac9c-71de-11e5-8917-fbf2d33d75e5.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10537265/d825ba24-73f0-11e5-918f-3daf47a119aa.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10537303/2708b2f4-73f1-11e5-947b-9bd98762db15.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10538086/5f4aa28a-73f6-11e5-894b-a2528a8a0886.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10538714/bf725f1e-73fa-11e5-9dfc-db51d267886e.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10538794/4f0655f4-73fb-11e5-8a7d-18a4da364b36.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539476/1a13d402-7400-11e5-9a0a-de6c70c759dd.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539496/31d36418-7400-11e5-9d83-129ab66f11be.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539515/4720fbdc-7400-11e5-8604-cbafb7fc0ec5.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539543/75d92454-7400-11e5-8ed2-0b7d7d7f3a8e.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539553/92dfb6e4-7400-11e5-86c7-c857ed0acb6c.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539559/9c9ffd60-7400-11e5-8899-7ead86f350d6.png)
![image](https://cloud.githubusercontent.com/assets/5658058/10539875/584012e2-7403-11e5-8269-30c46eb7b1ff.png)
![docker containers and dependencies in rage-analytics](https://cloud.githubusercontent.com/assets/5658058/10542929/d728a610-741b-11e5-9275-0c8409674e8a.jpg)

**Comment by gorco** [comment]
![1](https://cloud.githubusercontent.com/assets/5657407/10457685/a872f218-71c7-11e5-911c-8b5979d12a0a.png)
![2](https://cloud.githubusercontent.com/assets/5657407/10457687/a9c921e6-71c7-11e5-827c-51ea64781d6f.png)
![3](https://cloud.githubusercontent.com/assets/5657407/10457695/ac6a5942-71c7-11e5-928b-579d973d8816.png)
![4](https://cloud.githubusercontent.com/assets/5657407/10457697/adaf102c-71c7-11e5-8790-855955502144.png)
![5](https://cloud.githubusercontent.com/assets/5657407/10457698/af060368-71c7-11e5-9c03-a08d784fd6d2.png)
![6](https://cloud.githubusercontent.com/assets/5657407/10457701/b076ace8-71c7-11e5-85fa-0398323d7c18.png)
![7](https://cloud.githubusercontent.com/assets/5657407/10457702/b1a094da-71c7-11e5-86bd-4c7636a3b925.png)
![8](https://cloud.githubusercontent.com/assets/5657407/10457704/b2d4b85e-71c7-11e5-8a3e-b1fc838a380b.png)
![9](https://cloud.githubusercontent.com/assets/5657407/10457705/b3f25f48-71c7-11e5-89ac-0e97ed3c077b.png)
![10](https://cloud.githubusercontent.com/assets/5657407/10457708/b51a8de6-71c7-11e5-896e-62aac140af89.png)
![11](https://cloud.githubusercontent.com/assets/5657407/10457710/b67d68b6-71c7-11e5-9241-a08b2d7d0da6.png)
![12](https://cloud.githubusercontent.com/assets/5657407/10457712/b7fc4662-71c7-11e5-8f9c-de91b5189f0c.png)
![13](https://cloud.githubusercontent.com/assets/5657407/10457715/b967eb28-71c7-11e5-8c12-4d158bf38a58.png)
![14](https://cloud.githubusercontent.com/assets/5657407/10457717/ba84663a-71c7-11e5-9052-110fff950832.png)
![15](https://cloud.githubusercontent.com/assets/5657407/10457718/bbaa2ee6-71c7-11e5-8d99-a3c62ab94474.png)
![16](https://cloud.githubusercontent.com/assets/5657407/10457719/bcc423ea-71c7-11e5-8e19-498ed79f6cce.png)
![17](https://cloud.githubusercontent.com/assets/5657407/10457745/ce0f3ea0-71c7-11e5-9fad-904e9cd3e11e.png)
![18](https://cloud.githubusercontent.com/assets/5657407/10457751/d190a8f2-71c7-11e5-995a-ee4e120363d8.png)
![19](https://cloud.githubusercontent.com/assets/5657407/10457754/d31aba32-71c7-11e5-82a4-a3c4b8adc9e2.png)
![20](https://cloud.githubusercontent.com/assets/5657407/10457756/d4af0394-71c7-11e5-9db8-01bd6c543d0a.png)
![21](https://cloud.githubusercontent.com/assets/5657407/10457758/d5ec91d6-71c7-11e5-91c7-999501f307c7.png)
![22](https://cloud.githubusercontent.com/assets/5657407/10457760/d7486e24-71c7-11e5-8f58-a2bb80ac57bc.png)
![23](https://cloud.githubusercontent.com/assets/5657407/10457763/d8fe57ba-71c7-11e5-8f3b-4af72b9185b6.png)
![24](https://cloud.githubusercontent.com/assets/5657407/10457764/da2e5978-71c7-11e5-9e11-f10e9a6fc94c.png)
![25](https://cloud.githubusercontent.com/assets/5657407/10457767/db5df1dc-71c7-11e5-969e-0257d68fec3a.png)
![trackcode](https://cloud.githubusercontent.com/assets/5657407/10537391/c33a8026-73f1-11e5-81ca-92f616906b73.png)
![configureclass](https://cloud.githubusercontent.com/assets/5657407/10537605/42d267e4-73f3-11e5-83a2-2a1ea69b6d87.png)
![addstudent](https://cloud.githubusercontent.com/assets/5657407/10538021/fc524fb6-73f5-11e5-9948-a1da9a78663c.png)
![fileclass](https://cloud.githubusercontent.com/assets/5657407/10538213/4af549f6-73f7-11e5-804c-90de92264d22.png)
![link](https://cloud.githubusercontent.com/assets/5657407/10538892/faf55978-73fb-11e5-8cd7-49a6a13f41fd.png)
![a2manage](https://cloud.githubusercontent.com/assets/5657407/10539189/282d4458-73fe-11e5-9232-4ccc2377a90f.png)
![userstab](https://cloud.githubusercontent.com/assets/5657407/10539331/257dfb5c-73ff-11e5-9bac-aeec8227f0df.png)
![rolesview](https://cloud.githubusercontent.com/assets/5657407/10539400/a09d39d8-73ff-11e5-8213-3cdbf8851372.png)
![applicationsview](https://cloud.githubusercontent.com/assets/5657407/10539399/a09ce780-73ff-11e5-947e-8a5758593148.png)
![openlrsdashboard](https://cloud.githubusercontent.com/assets/5657407/10545179/adab365c-7427-11e5-8e7e-d9029dd63066.png)

**Comment by manuel-freire** [comment]
![docker containers and dependencies in rage-analytics](https://cloud.githubusercontent.com/assets/2271676/10543524/d4dd656e-741e-11e5-87b0-9018a9b251e2.png)

**Comment by gorco** [comment]
![server](https://cloud.githubusercontent.com/assets/5657407/12704640/8cc29a7a-c85f-11e5-988e-4140cfc397d7.png)

**Comment by RotaruDan** [comment]
Dashboards & plugins
![rage_analytics_dashboard_plugins](https://cloud.githubusercontent.com/assets/5658058/12705774/1ddd21e4-c877-11e5-8d56-43b0da602477.png)
Dev process
![rage_analytics_dev_process](https://cloud.githubusercontent.com/assets/5658058/12705777/2a0fb5f8-c877-11e5-8220-f9706dc5adcc.png)
Build Process
![rage_analytics_build_process](https://cloud.githubusercontent.com/assets/5658058/12705776/250e20a8-c877-11e5-8c83-cb55ba020a47.png)

**Comment by RotaruDan** [comment]
![image00](https://cloud.githubusercontent.com/assets/5658058/13121374/66a9c22c-d5b2-11e5-9e86-bc28c4476d9e.png)
![image01](https://cloud.githubusercontent.com/assets/5658058/13121389/7174889a-d5b2-11e5-9065-fe9903bbdd50.png)

**Comment by RotaruDan** [comment]
![docker containers and dependencies in rage-analytics](https://cloud.githubusercontent.com/assets/5658058/14140714/fb5b18d8-f67a-11e5-9b9c-41efd9277ee1.png)

**Comment by RotaruDan** [comment]
![all_session](https://cloud.githubusercontent.com/assets/5658058/16236604/4f932978-37d9-11e6-9421-c1546b9e7a36.png)
![all_singleplayer](https://cloud.githubusercontent.com/assets/5658058/16236605/4ff3ee3e-37d9-11e6-928c-695f5305eced.png)
![alternatives_count_session](https://cloud.githubusercontent.com/assets/5658058/16236607/5035ee06-37d9-11e6-88d3-bbba76c0880f.png)
![alternatives_count_singleplayer](https://cloud.githubusercontent.com/assets/5658058/16236606/5035bf76-37d9-11e6-945e-4bbadf27d90a.png)
![alternatives_responses_session](https://cloud.githubusercontent.com/assets/5658058/16236609/5036e216-37d9-11e6-8ca7-c6a91c67f321.png)
![alternatives_responses_singleplayer](https://cloud.githubusercontent.com/assets/5658058/16236611/50429354-37d9-11e6-9cb6-b32bb2169b87.png)
![player_activity_over_time_singleplayer](https://cloud.githubusercontent.com/assets/5658058/16236610/503bcf6a-37d9-11e6-8756-d87439c3c6b3.png)
![players_activity_over_time_session](https://cloud.githubusercontent.com/assets/5658058/16236608/503684ce-37d9-11e6-80b0-819a0c970fec.png)
![xapi_verbs_session](https://cloud.githubusercontent.com/assets/5658058/16236612/50506718-37d9-11e6-9c6b-9d70e272ccb9.png)
![xapi_verbs_singleplayer](https://cloud.githubusercontent.com/assets/5658058/16236613/5055a840-37d9-11e6-8cb7-a066e9dc8b42.png)
![1_select_analysis](https://cloud.githubusercontent.com/assets/5658058/16236614/505a8c16-37d9-11e6-922f-cf98d3b5a9d5.png)
![2_select_index](https://cloud.githubusercontent.com/assets/5658058/16236615/505cf8c0-37d9-11e6-9e29-22610856feb7.png)
![3_select_visualizations](https://cloud.githubusercontent.com/assets/5658058/16236616/505f0700-37d9-11e6-914e-f34ad928f39c.png)
![4_configure_fields](https://cloud.githubusercontent.com/assets/5658058/16236617/5065250e-37d9-11e6-9073-2aba0b16c4e6.png)
![activity_count_per_player_session](https://cloud.githubusercontent.com/assets/5658058/16236618/506ec51e-37d9-11e6-8feb-3506877808b2.png)
![activity_count_per_player_singleplayer](https://cloud.githubusercontent.com/assets/5658058/16236619/507649c4-37d9-11e6-9582-6c347f96fc96.png)

**Comment by RotaruDan** [comment]
[statements.txt](https://github.com/RotaruDan/rage-analytics/files/326087/statements.txt)

**Comment by RotaruDan** [comment]
![activity_session](https://cloud.githubusercontent.com/assets/5658058/16264502/52d8fd6e-387a-11e6-9a1b-c2eae32220a9.png)

**Comment by RotaruDan** [comment]
![average_score_per_player](https://cloud.githubusercontent.com/assets/5658058/16264793/d1429a9c-387b-11e6-8087-babd28e8909e.png)
![different_alternatives_preferred](https://cloud.githubusercontent.com/assets/5658058/16264794/d15697ae-387b-11e6-93dc-1bc08fec424d.png)
![total_session_players](https://cloud.githubusercontent.com/assets/5658058/16264796/d16ae29a-387b-11e6-861e-5ebb8218ada0.png)
![total_session_traces_count](https://cloud.githubusercontent.com/assets/5658058/16264795/d1661152-387b-11e6-97da-5cd55c064d43.png)

**Comment by RotaruDan** [comment]
![no_results](https://cloud.githubusercontent.com/assets/5658058/16336580/d648b76c-3a0e-11e6-859e-d8b41a618db8.png)
![time_frame](https://cloud.githubusercontent.com/assets/5658058/16336581/d6490636-3a0e-11e6-864a-f17316dcf40d.png)

**Comment by gorco** [comment]
![rage-logo-high-res](https://cloud.githubusercontent.com/assets/5657407/16461734/4620add8-3e2e-11e6-95aa-ee9232a3afe3.png)
![logo_rage_top-of-the-web](https://cloud.githubusercontent.com/assets/5657407/16461800/9ae669fc-3e2e-11e6-97f4-4e93f2c96dea.jpg)

**Comment by crisal24** [comment]
![realtime_updated](https://cloud.githubusercontent.com/assets/19714314/19039433/320d2806-8980-11e6-8d96-0a0c9b4df91c.png)

**Comment by crisal24** [comment]
![architecture-3-style-unified-and-updated pptx](https://cloud.githubusercontent.com/assets/19714314/19107312/e18ce494-8aeb-11e6-8b20-2371bed7290c.png)
![architecture-3-style-unified-and-updated pptx 1](https://cloud.githubusercontent.com/assets/19714314/19107313/e37be3e0-8aeb-11e6-8d24-d8c7a711856a.png)
![architecture-3-style-unified-and-updated pptx](https://cloud.githubusercontent.com/assets/19714314/19107842/79857a0c-8aee-11e6-8566-9147a8dccb1b.png)
![architecture-3-style-unified-and-updated pptx 3](https://cloud.githubusercontent.com/assets/19714314/19107317/e7a615e4-8aeb-11e6-9cc8-e8496019f972.png)
![architecture-3-style-unified-and-updated pptx 4](https://cloud.githubusercontent.com/assets/19714314/19107319/e95da8ca-8aeb-11e6-9c56-0f312e2e8239.png)
![architecture-3-style-unified-and-updated pptx 5](https://cloud.githubusercontent.com/assets/19714314/19107320/eae01d18-8aeb-11e6-9ae6-a39cb1986d1c.png)
![architecture-3-style-unified-and-updated pptx 6](https://cloud.githubusercontent.com/assets/19714314/19107323/ed5aba4e-8aeb-11e6-9a20-3bbe39d35a21.png)
![architecture-3-style-unified-and-updated pptx 7](https://cloud.githubusercontent.com/assets/19714314/19107325/eede487c-8aeb-11e6-9b2a-7fd3184b14ec.png)
![architecture-3-style-unified-and-updated](https://cloud.githubusercontent.com/assets/19714314/19108724/301c3a00-8af2-11e6-9762-a53660c0594f.png)

**Comment by crisal24** [comment]
![add_game_links_1](https://cloud.githubusercontent.com/assets/19714314/19109870/94c2f52a-8af7-11e6-8c6a-56556fb4c379.png)
![add_game_link_2](https://cloud.githubusercontent.com/assets/19714314/19110239/2886c538-8af9-11e6-94b9-b3b42578cf52.png)
![add_game_link_22](https://cloud.githubusercontent.com/assets/19714314/19110142/d4354180-8af8-11e6-8259-888570844032.png)
![firstaidgame_analysis_config](https://cloud.githubusercontent.com/assets/19714314/19113812/995e0ed0-8b0b-11e6-8040-6416b00a7b78.png)
![users_table](https://cloud.githubusercontent.com/assets/19714314/19113815/9a75f292-8b0b-11e6-9722-27bf30bb2330.jpg)

**Comment by crisal24** [comment]
![teacher_visualizations_1](https://cloud.githubusercontent.com/assets/19714314/19185206/e555ec9c-8c80-11e6-8f3a-f52d69967257.png)
![teacher_visualizations_2](https://cloud.githubusercontent.com/assets/19714314/19185207/e674bad6-8c80-11e6-8969-542e747cc08d.png)
![teacher_visualizations_3](https://cloud.githubusercontent.com/assets/19714314/19185208/e7a07706-8c80-11e6-96b6-0a3a96f314cc.png)
![developer_visualizations_1](https://cloud.githubusercontent.com/assets/19714314/19185210/e976c63e-8c80-11e6-9fc7-a45b12ccb8fe.png)
![developer_visualizations_2](https://cloud.githubusercontent.com/assets/19714314/19185212/eadfa950-8c80-11e6-9bc0-50b6ffd04ff9.png)
![developer_visualizations_3](https://cloud.githubusercontent.com/assets/19714314/19185214/ec7cfd6c-8c80-11e6-9129-f152f4813f7c.png)
![lrs_analytics_firstaid](https://cloud.githubusercontent.com/assets/19714314/19187046/a3370e46-8c89-11e6-92bc-3bdccf2663a0.png)
![applications list](https://cloud.githubusercontent.com/assets/19714314/19187337/2898ee64-8c8b-11e6-8cb4-6508f1c22612.png)
![roles](https://cloud.githubusercontent.com/assets/19714314/19187341/2b342ddc-8c8b-11e6-8a92-ec6a8b6b8f51.png)

**Comment by crisal24** [comment]
![warning and alerts general and user](https://cloud.githubusercontent.com/assets/19714314/20304488/c9f02426-ab30-11e6-8c0f-6486db07f402.png)

**Comment by RotaruDan** [comment]
![image](https://cloud.githubusercontent.com/assets/5658058/21310501/ef834f84-c5e2-11e6-8809-6ebacd2044d2.png)

**Comment by gorco** [comment]
![1true](https://cloud.githubusercontent.com/assets/5657407/21312248/58f3c6f8-c5eb-11e6-95ad-ded730e2417a.png)
![2true](https://cloud.githubusercontent.com/assets/5657407/21312250/5ab326d2-c5eb-11e6-92cd-fcab2c8ee454.png)
![3true](https://cloud.githubusercontent.com/assets/5657407/21312251/5c1679e8-c5eb-11e6-872b-0cc7b3b071c8.png)
![4true](https://cloud.githubusercontent.com/assets/5657407/21312255/5df366b8-c5eb-11e6-81ed-ac42c7f3e53b.png)
![5true](https://cloud.githubusercontent.com/assets/5657407/21312259/605e9742-c5eb-11e6-8006-7c17eacf4eae.png)
![5-1](https://cloud.githubusercontent.com/assets/5657407/21312260/624d72ee-c5eb-11e6-88a5-3bf69dcd4271.png)
![6](https://cloud.githubusercontent.com/assets/5657407/21312262/6445d474-c5eb-11e6-95e3-ba826fd0c7ac.png)
![7](https://cloud.githubusercontent.com/assets/5657407/21312265/65f67d1e-c5eb-11e6-9d33-c4c3e3debdde.png)
![8](https://cloud.githubusercontent.com/assets/5657407/21312266/67db898a-c5eb-11e6-971a-b6570c13566f.png)
![9](https://cloud.githubusercontent.com/assets/5657407/21312268/693e3cbe-c5eb-11e6-8fd4-bcbc52151a6f.png)

**Comment by gorco** [comment]
![unitytracker add tracker](https://cloud.githubusercontent.com/assets/5657407/21893124/07974d46-d8da-11e6-9168-e1cb0e7547f1.png)
![inspector unity](https://cloud.githubusercontent.com/assets/5657407/21893123/07972abe-d8da-11e6-8f79-94903f62dced.png)

**Comment by crisal24** [comment]
![icon_analytics_developer](https://cloud.githubusercontent.com/assets/19714314/23360406/65c277c6-fceb-11e6-909b-3fb13b91fd82.png)
![icon_game_developer](https://cloud.githubusercontent.com/assets/19714314/23360417/6c9e83f0-fceb-11e6-918b-fd0718065a5b.png)
![icon_know_all](https://cloud.githubusercontent.com/assets/19714314/23360418/6d5859a6-fceb-11e6-9598-a686c7e6b6f7.png)

**Comment by crisal24** [comment]
![rage new logo](https://cloud.githubusercontent.com/assets/19714314/23263715/60474132-f9df-11e6-8621-50f4c327bcb2.png)

**Comment by crisal24** [comment]
![teacher_player_progress_level_game](https://cloud.githubusercontent.com/assets/19714314/23369615/4492291c-fd12-11e6-8d5c-28d8ad629b15.png)

**Comment by crisal24** [comment]
![scoreboard](https://cloud.githubusercontent.com/assets/19714314/23608231/b7e2d096-0268-11e7-933d-292b178caa1c.png)
![scoremax](https://cloud.githubusercontent.com/assets/19714314/23608232/b92e82a6-0268-11e7-8840-3807026808e8.png)

**Comment by gorco** [comment]
![architecture-3-style-unified-and-updated pptx](https://user-images.githubusercontent.com/5657407/28160045-4a483136-67bf-11e7-941e-2db0cd786869.png)

**Comment by gorco** [comment]
![gas](https://user-images.githubusercontent.com/5657407/28458707-0a7f7e7c-6e0b-11e7-9874-f3e7d625e5e9.png)
![ragegaslogos](https://user-images.githubusercontent.com/5657407/28458708-0a9d8854-6e0b-11e7-96ba-c1506d31f4e3.png)

**Comment by crisal24** [comment]
![alertas_general](https://user-images.githubusercontent.com/19714314/29449118-ce498e8e-83f9-11e7-946f-fd4fb6b45306.png)
![alertas_general_usuario](https://user-images.githubusercontent.com/19714314/29449120-ce6fb960-83f9-11e7-8541-6c2d460253c3.png)
![alertas_usuario](https://user-images.githubusercontent.com/19714314/29449119-ce693f4a-83f9-11e7-82dd-3375b57291ce.png)
![teacher1](https://user-images.githubusercontent.com/19714314/29449126-d306d242-83f9-11e7-886c-fdf000c3797b.PNG)
![teacher2](https://user-images.githubusercontent.com/19714314/29449125-d305e120-83f9-11e7-9179-04da147278a2.PNG)
![teacher3](https://user-images.githubusercontent.com/19714314/29449124-d305d176-83f9-11e7-9670-dfcddd887adc.PNG)

**Comment by crisal24** [comment]
![icon_user](https://user-images.githubusercontent.com/19714314/30169246-1ac938a2-93ec-11e7-9022-12929c4b24f0.png)
![developer](https://user-images.githubusercontent.com/19714314/30171616-c105b6a4-93f2-11e7-879e-10c5d0ffa921.png)
![game guide](https://user-images.githubusercontent.com/19714314/30171621-c656735a-93f2-11e7-881e-83c93044aac8.png)
![warnings](https://user-images.githubusercontent.com/19714314/30171626-cb2738f6-93f2-11e7-9e57-e46dc97344fd.png)
![public game](https://user-images.githubusercontent.com/19714314/30171636-d13309f0-93f2-11e7-89c4-9ac70ef35447.png)
![analytics setup](https://user-images.githubusercontent.com/19714314/30171652-dccc1928-93f2-11e7-8a65-6198e2cca873.png)
![developer real time](https://user-images.githubusercontent.com/19714314/30171672-e734df30-93f2-11e7-9656-dc4012e17abf.png)
![main teacher](https://user-images.githubusercontent.com/19714314/30171677-eb2a41b6-93f2-11e7-80f9-55ee2cf76f6f.png)
![class view](https://user-images.githubusercontent.com/19714314/30171690-ef9199fc-93f2-11e7-9317-fc9217ebcd08.png)
![activity information](https://user-images.githubusercontent.com/19714314/30171696-f4aa0e1a-93f2-11e7-9d74-c856c28aabb5.png)
![activity students](https://user-images.githubusercontent.com/19714314/30171705-f9f1ef28-93f2-11e7-826a-1533de32b165.png)
![activity real time](https://user-images.githubusercontent.com/19714314/30171707-fb4906b8-93f2-11e7-86f5-8a7c49c1cf5a.png)

**Comment by crisal24** [comment]
![webhook](https://user-images.githubusercontent.com/19714314/35278044-acd8f654-0040-11e8-8d20-914a530505e3.png)
![eventtype](https://user-images.githubusercontent.com/19714314/35278045-ae144adc-0040-11e8-8db2-71f9e86934fd.png)

**Comment by crisal24** [comment]
![xapi_trace](https://user-images.githubusercontent.com/19714314/37199728-6ae25a9e-237a-11e8-8340-4b696ac09351.png)
![table_traces](https://user-images.githubusercontent.com/19714314/37199738-6fb8c300-237a-11e8-9159-9f942a60cb0e.png)

**Comment by crisal24** [comment]
![teacherrole](https://user-images.githubusercontent.com/19714314/38863629-c7b12c70-4227-11e8-93cd-753b523fe009.png)
![developerrole](https://user-images.githubusercontent.com/19714314/38863636-caacef54-4227-11e8-9014-fbb21a4ead47.png)

**Comment by crisal24** [comment]
![1-general](https://user-images.githubusercontent.com/19714314/39175727-9739a946-479a-11e8-862d-babd176a209d.png)
![2-answers](https://user-images.githubusercontent.com/19714314/39175738-9a1a304a-479a-11e8-80de-143ef0fc3d1a.png)
![3-scores](https://user-images.githubusercontent.com/19714314/39175741-9bf80644-479a-11e8-8867-b27c6c0b20b6.png)
![4-progress](https://user-images.githubusercontent.com/19714314/39175744-9d7194d6-479a-11e8-9de0-a0488cc9c2c8.png)
![5-location](https://user-images.githubusercontent.com/19714314/39865462-7d69bdea-543c-11e8-9b74-6c7bcba1f31b.png)

**Comment by crisal24** [comment]
![thomaskilmann1](https://user-images.githubusercontent.com/19714314/40913243-7f765a8e-67e3-11e8-9e05-df9a6b1824b8.png)
![thomaskilmann2](https://user-images.githubusercontent.com/19714314/40913244-7f9c5ffe-67e3-11e8-90e4-4c406a29a073.png)
![thomaskilmann3](https://user-images.githubusercontent.com/19714314/40913245-7fbb1822-67e3-11e8-9e53-6d1aeec76f09.png)
![thomaskilmann4](https://user-images.githubusercontent.com/19714314/40913246-7fdb182a-67e3-11e8-916b-2c1e55719eac.png)
![thomaskilmann5](https://user-images.githubusercontent.com/19714314/40913247-7ffb5176-67e3-11e8-896d-5d2c25a3ccce.png)

**Comment by crisal24** [comment]
![frontend01-myclass](https://user-images.githubusercontent.com/19714314/47998797-cff52800-e100-11e8-8fc7-5d67c5e4f802.png)
![frontend02-configureyourclassparticipants](https://user-images.githubusercontent.com/19714314/47998799-d2578200-e100-11e8-8b0b-36adaf22cb11.png)
![frontend03-configureparticipants](https://user-images.githubusercontent.com/19714314/47998801-d4214580-e100-11e8-8b0a-12f5ac742934.png)
![frontend04-addgroup](https://user-images.githubusercontent.com/19714314/47998808-d7b4cc80-e100-11e8-9fb6-bfcdcf0e8389.png)
![frontend05-groupadded](https://user-images.githubusercontent.com/19714314/47998809-d84d6300-e100-11e8-8141-3c0d291e3152.png)
![frontend06-usinggroups](https://user-images.githubusercontent.com/19714314/47998810-d84d6300-e100-11e8-9caa-5a5782c26284.png)
![frontend07-usegroupinclass](https://user-images.githubusercontent.com/19714314/47998811-d84d6300-e100-11e8-9b24-22e7af813145.png)
![frontend08-addgrouping](https://user-images.githubusercontent.com/19714314/47998812-d84d6300-e100-11e8-9fa7-e3356c0bc3a3.png)
![frontend09-groupingadded](https://user-images.githubusercontent.com/19714314/47998814-d8e5f980-e100-11e8-968f-8435e5ea74b8.png)
![frontend10-usinggroupings](https://user-images.githubusercontent.com/19714314/47998815-d8e5f980-e100-11e8-8543-76315d8c1cdc.png)
![frontend11-usinggroupinginclass](https://user-images.githubusercontent.com/19714314/47998816-d8e5f980-e100-11e8-82b8-5f2cc93aa807.png)
![frontend12-usinggroups](https://user-images.githubusercontent.com/19714314/47998817-d8e5f980-e100-11e8-8962-fb6df3e88c62.png)
![frontend13-usinggroupins](https://user-images.githubusercontent.com/19714314/47998818-d8e5f980-e100-11e8-9aee-59e1476739e6.png)
![frontend14-participantsgroups](https://user-images.githubusercontent.com/19714314/47998820-d97e9000-e100-11e8-8cb0-76c0c969e19f.png)
![frontend15-participantsgroupings](https://user-images.githubusercontent.com/19714314/47998821-d97e9000-e100-11e8-8d7e-5ee94b1c6c69.png)

**Comment by RotaruDan** [comment]
![image5](https://user-images.githubusercontent.com/5658058/52058318-7d909f80-2567-11e9-94f6-6bf32c485eed.png)
![image1](https://user-images.githubusercontent.com/5658058/52058339-85504400-2567-11e9-8746-ddbc3f180d23.png)
![image2](https://user-images.githubusercontent.com/5658058/52058341-85504400-2567-11e9-8b2c-9cc72892b7cb.png)
![image3](https://user-images.githubusercontent.com/5658058/52058342-85504400-2567-11e9-8f67-0075419a7a2e.png)
![image4](https://user-images.githubusercontent.com/5658058/52058343-85e8da80-2567-11e9-93fa-b0dfba05eb81.png)
![image6](https://user-images.githubusercontent.com/5658058/52058344-85e8da80-2567-11e9-91a7-7c112ca6a7f1.png)

![photo_2019-01-31_15-01-51](https://user-images.githubusercontent.com/5658058/52059098-33102280-2569-11e9-980a-9f99d01d5c4b.jpg)

**Comment by RotaruDan** [comment]
[results.xlsx](https://github.com/RotaruDan/rage-analytics/files/2817519/results.xlsx)

**Comment by RotaruDan** [comment]
![image3](https://user-images.githubusercontent.com/5658058/52060297-32c55680-256c-11e9-9a5a-32dc3837e325.png)
![image1](https://user-images.githubusercontent.com/5658058/52060298-32c55680-256c-11e9-9f21-ec886a633a14.png)
![image2](https://user-images.githubusercontent.com/5658058/52060299-32c55680-256c-11e9-8baa-b02a4f7ccaa1.png)

**Comment by RotaruDan** [comment]
![image1](https://user-images.githubusercontent.com/5658058/52081271-16d8a980-259a-11e9-8872-eb8c2d46f5d8.jpg)
